name: correlation-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - bottleneck
  - jupyterlab
  - tqdm
  - psutil
  - lxml
  - pip:
    - obspy
