name: eqtm
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - pandas
  - bottleneck
  - fastavro
  - python-snappy
  - fastparquet
  - tqdm
  - psutil
  - pip:
    - obspy
    - cupy
