name: correlation-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - matplotlib
  - bottleneck
  - jupyterlab
  - tqdm
  - psutil
  - fastavro
  - python-snappy
  - numba
  - scikit-learn
  - xgboost
  - optuna
  - fastparquet
  - shap
  - nodejs
  - ipywidgets
  - plotly
  - obspy
